application: id-feed
version: 1
runtime: python
api_version: 1
default_expiration: "30d"

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: .*
  script: main.py
